import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Navbar from "@/components/Header/Navbar";
import { Toaster } from "react-hot-toast";
import AuthContextProvider from "@/context/AuthContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Banglink",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-200 min-h-screen`}
      >
        <AuthContextProvider>
          <Header></Header>
          <Navbar></Navbar>
            <div className="px-10 py-5">
              {children}
            </div>
          <Toaster position="top-center" reverseOrder={false}/>
        </AuthContextProvider>
      </body>
    </html>
  );
}
